server:
  address: localhost
  port: 8090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    properties:
      hibernate:
        default_schema: public
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    default-schema: public
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
